TOOLS_DIR := $(TRAVIS_BUILD_DIR)/tools
EIGEN_DIR := $(TOOLS_DIR)/eigen
BOOST_DIR := $(TOOLS_DIR)/boost
PROTOBUF_DIR := $(TOOLS_DIR)/protobuf
GPERFTOOLS_DIR := $(TOOLS_DIR)/gperftools
CXXFLAGS := $(CXXFLAGS) -I $(EIGEN_DIR)/include -I $(BOOST_DIR)/include -I $(PROTOBUF_DIR)/include
LDLIBS := -L $(BOOST_DIR)/lib -L $(GPERFTOOLS_DIR)/lib -L $(PROTOBUF_DIR)/lib $(LDLIBS)
